[package]
name = "zalkanes-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "zalkanes"
path = "src/main.rs"

[dependencies]
zalkanes-core    = { workspace = true }
zalkanes-chain   = { workspace = true }
zalkanes-indexer = { workspace = true }
zalkanes-rpc     = { workspace = true }
zalkanes-tx      = { workspace = true }
zalkanes-build   = { workspace = true }
zalkanes-state   = { workspace = true }
zalkanes-protocol = { workspace = true }
zalkanes-runtime = { workspace = true }
zalkanes-carrier = { workspace = true }
zalkanes-wallet  = { workspace = true, features = ["shielded"] }
age              = { version = "=0.12.1", default-features = false }
rpassword        = { version = "=7.3.1" }
anyhow           = { workspace = true }
tokio            = { workspace = true }
clap             = { workspace = true }
tracing          = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json       = { workspace = true }
hex              = { workspace = true }
reqwest          = { workspace = true }
zcash_transparent = { workspace = true }
zcash_protocol   = { workspace = true }
sha2             = { workspace = true }
