[package]
name = "zalkanes-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zalkanes-core = { workspace = true }
zalkanes-state = { workspace = true }
wasmi = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
wat = { version = "=1.258.0" }
